### PR TITLE
add promise support

### PR DESCRIPTION
**Pull request by nbransby**
This commit adds support for returning promises from the operation functions if a callback is not supplied.

Im aware this is a breaking change as operations called by existing code which does not pass a callback (or passes undefined) will not execute. 

It is still possbile to execute the operation without a callback though by passing null or false instead of omitting the arg

### CODE REVIEW

**Comment by alevy** [comment]
I suspect not supporting calls with no callback is not a big deal, and supporting promises seems important. Will leave this up to see if anyone yells at us about this, but are you able to fix the build error meanwhile?

**Comment by nbransby** [comment]
Yes it's due to use of arrow function will fix tonight

**Comment by sushantbs** [comment]
Any updates on the status of this?

**Comment by nbransby** [comment]
I got all the tests passing except for 2 but I think these failing have nothing to do with the changes I made @alevy ? https://travis-ci.org/alevy/memjs/jobs/234402402

**Comment by alevy** [comment]
Yes I think it's only still including that test because there is a conflict that needs to be resolved to merge with current master (which doesn't include the failing tests).

I'll resolve and merge.

**Comment by ovidiusabou** [comment]
are you going to release a new version with this? it looks really useful

**Comment by alevy** [comment]
Yes, I'll do that now. Will publish a non-RC 1.0 first, then bump to 1.1 RC. Sound reasonable?

**Comment by ovidiusabou** [comment]
Yes, but please also look at https://github.com/alevy/memjs/pull/106 first

**Pull request merged**
