### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by miccolis**
PR has [eslint](http://eslint.org/) run as part of npm test and fixes the various style inconsistencies it finds.   This should probably be extended to the test code as well, but I wanted to float the idea of adding this before making the PR larger.

### CODE REVIEW

**Comment by alevy** [comment]
Looks like there is an issue installing a dependency of `eslint` called `chalk` with node version 0.8

**Comment by alevy** [comment]
If that's hard to fix, I wouldn't mind merging the lint changes themselves without adding the linter to the test suite yet (although that would obviously be even better)

**Comment by miccolis** [comment]
@alevy yea, it's looking like trying to get eslint working with node 0.8 is a non-starter. I'm happy to remove the linting from `npm test`, but before I do... any chance I can convince you to deprecate v0.8 support? The [last release was july 2014](https://nodejs.org/download/release/v0.8.28/) and it's no longer maintained at all. That said I understand a change like that would demand major release, etc...

**Comment by alevy** [comment]
@miccolis I can definitely be pushed that way. Heroku (which hosts the vast majority of users of `memjs` I'm aware of) no longer supports 0.8 and after asking around a bit it seems like the right thing to do. I'm doing some tweaks with travis in a separate branch, so I think we can go a head and merge this, and deprecate 0.8 separately

**Comment by miccolis** [comment]
Sounds good, let me know if you need anything else here.

**Pull request merged**
