### PR TITLE
Avoid mandatory option fields

### PR DESCRIPTION
**Pull request by Shudrum**
I've done the work for SET, ADD & REPLACE.

For example, when you use SET, those two calls are deprecated:

```js
client.set('key', 'value', (err, result) => {});

client.set('key', 'value', (err, result) => {}, 60);
```

The first one should be available and not deprecated, if a user do not want to specify the expiration, he should use SET like this:

```js
client.set('key', 'value', {}, (err, result) => {});
```

This pull request allow, without deprecated warning, the use of those two;

```js
client.set('key', 'value', {}, (err, result) => {});

client.set('key', 'value', (err, result) => {});
```

To avoid specifying an empty object.

### CODE REVIEW

**Comment by alevy** [comment]
I think we've had these deprecation warnings for long enough that we can just remove the old version of the argument ordering and bump the version number sufficiently. In that case, it seems palatable to allow a single argument (`options`) to be left out and check for that case. I feel less good about trying to cover all ways someone might want to invoke these functions with an ever increasing set of `if-else` checks.

Thoughts? Would you be open to replacing the deprecation checks with the version you propose (and no deprecation warning?)

**Comment by Shudrum** [comment]
I really prefer removing the deprecation if you want to.

The if/else hell is dangerous in that case and the code can be way more readable. (Also I haven't cover each cases).

I can do the job if you want yes! Just wait a little bit, I haven't so much time next days.

**Comment by Shudrum** [comment]
And after, don't forget to change the version to the next major. (Yes, stupid advice, but some people miss it).

**Comment by Shudrum** [comment]
Increment / Decrement options no longer mandatory too.
Deprecations removed and tests updated.

I've also modified the changelog and the version. If you want, I can remove it.

**Comment by alevy** [comment]
@Shudrum looks good overall. Since this is bumping to Version 1.0 (which is somewhat meaningful), it might mean not immediately pushing this to npm (but rather going through a short period to surface complaints). Sound reasonable?

**Comment by Shudrum** [comment]
@alevy completely reasonable!

**Pull request merged**
